spring.jpa:
  database: H2
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: true
  generate-ddl: true

spring.datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MVCC=FALSE;MODE=PostgreSQL
  username: sa
  password: sa

facebook:
  clientId: changeme
  clientSecret: changeme
  accessTokenUri: https://graph.facebook.com/oauth/access_token
  userAuthorizationUri: https://www.facebook.com/dialog/oauth
  userInfoUri: https://graph.facebook.com/me

jwt.token:
  issuer: changeme
  signing.key: changeme